version: '3.9'

services:
  nodejs:
    container_name: nodejs_app
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    depends_on:
      - postgres
      - redis


  postgres:
    image: postgres
    container_name: postgres_db